### ISSUE TITLE
Error with spinner

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-cli#308]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
`jovo build:platform alexa` should build the model.

## Current Behavior
An error related with an internal library is thrown.

### Error log
```
$ jovo build:platform alexa --stage local --ask-profile apd-local --clean
                                                                                
jovo build:platform: Build platform-specific language models based on Jovo models folder
  >> Learn more: https://jovo.tech/docs/cli/build
🚧 Initializing build process
                                                                                
x Error: --------------------------------------------------------------------------------
›                                                                                 
› Message:
›  this.spinner.stream.cursorTo is not a function
›                                                                                 
› Module:
›  JovoCliCore
›                                                                                 
›                                                                                 
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.
```

## Your Environment

* Jovo CLI version used: @jovotech/cli/4.1.0 
* Operating System: linux-x64 node-v14.19.0

I'm using this docker image: **andreysenov/node-gyp:8.4.1-node-14-alpine**

## Workaround solution
Run the build script like this to simulate a TTY:
`script build_log -c "jovo build:platform alexa --stage local --ask-profile apd-local --clean"`
Then you can see the result:
`cat build_log`

## Possible solution on Docker side (can't confirm yet)
[Use `-it` flags when running the imagen in Docker](https://docs.docker.com/engine/reference/commandline/run/#assign-name-and-allocate-pseudo-tty---name--it). (I can't confirm yet because GitLab manages it in the Runner and I can't access it's configuration in our servers yet)

**Comment by jrglg** [comment]
Curiously it works if I run the image alone in my Docker on my PC, but I can see some problem with icons:

![image](https://user-images.githubusercontent.com/52841892/153593308-6a6a2c5f-1c5b-416d-a327-d660f5457568.png)

What could be different from running it in a GitLab CI runner? I have to ask my colleges from the other department.

Anyway, these are the commands that I run:

```
npm config set prefix .npm_global_cache
npm install -g --cache .npm_global_cache --prefer-offline pnpm
export PATH=.npm_global_cache/bin:$PATH
pnpm config set store-dir .pnpm_store
npm install -g --cache .npm_global_cache --prefer-offline ask-cli@2.26.0 @assistant/gactions@3.2.1 @jovotech/cli@4.1.0
pnpm install --prefer-offline
jovo build:platform alexa --stage local --ask-profile apd-local --clean
```

This is my temporal pipeline for GitLab CI
(the `source global_packages.pipeline` has this):
```
LOCAL_PACKAGE_PNPM=pnpm@6.30.1
LOCAL_PACKAGE_ASK_CLI=ask-cli@2.26.0
LOCAL_PACKAGE_GACTIONS_CLI=@assistant/gactions@3.2.1
LOCAL_PACKAGE_JOVO_CLI=@jovotech/cli@4.1.0
```

```
stages:
  - build_local

default:
  image: andreysenov/node-gyp:8.4.1-node-14-alpine
  cache: &cache
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .npm_global_cache
      - .pnpm_store
      - node_modules/
    policy: pull

before_script:
  - source global_packages.pipeline
  - npm config set prefix .npm_global_cache
  - npm install -g --cache .npm_global_cache --prefer-offline $LOCAL_PACKAGE_PNPM
  - export PATH=.npm_global_cache/bin:$PATH
  - pnpm config set store-dir .pnpm_store

install_local:
  stage: .pre
  cache:
    <<: *cache
    policy: push
  script:
    - npm install -g --cache .npm_global_cache --prefer-offline $LOCAL_PACKAGE_ASK_CLI $LOCAL_PACKAGE_GACTIONS_CLI $LOCAL_PACKAGE_JOVO_CLI
    - pnpm install --prefer-offline # --frozen-lockfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "pruebas-ci"'
      changes:
        - global_packages.pipeline
        - package.json
        - pnpm-lock.yaml
  interruptible: true


build_local_alexa:
  stage: build_local
  script:
    - export ASK_DEFAULT_PROFILE=apd-local
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - pwd
    - whoami
    - ls -al
    - jovo build:platform alexa --stage local --ask-profile apd-local --clean
  rules:
    - if: '$CI_COMMIT_REF_NAME == "pruebas-ci"'
  # artifacts:
  #   - not yet
  interruptible: true

```
